# Project information
site_name: 'bimU.io User Guide'
site_description: 'bimU.io User Guide'
site_author: 'Transformosa Private Limited'
site_url: 'http://docs.bimu.io'

# Repository
# repo_name: 'Transformosa/bimU-io-docs'
# repo_url: 'https://github.com/Transformosa/bimU-io-docs'

# Copyright
copyright: 'Copyright &copy; 2021 Transformosa Private Limited'

# Documentation and theme
theme:
  name: material
  custom_dir: theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon-32x32.png
  logo: images/logo.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: globe
      link: https://bimu.io
    - type: youtube
      link: https://www.youtube.com/channel/UCW4NVA53RqJUfjJe3gao1kA
    - type: medium
      link: https://medium.com/transformosa-blog
    - type: facebook
      link: https://www.facebook.com/transformosa
    - type: twitter
      link: https://twitter.com/TransformosaUK
    - type: linkedin
      link: https://www.linkedin.com/company/transformosa
    
  # disqus: ''

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta

# Page tree
nav:
  - bimU.io Viewer: index.md
  - Log in to bimU.io: viewer/log-in-to-bimu-viewer.md
  - Manage BIM Models: viewer/manage-bim-models.md
  - Upload a BIM model: viewer/upload-a-bim-model.md
  - Navigate Using Web Viewer: viewer/navigate-using-web-viewer.md
  - Embed in Other Applications: viewer/embed-in-other-applications.md
  - Release Notes: viewer/release-notes.md
  - Terms of Service: viewer/terms-of-service.md
  - Privacy Policy: viewer/privacy-policy.md
  - bimU.io Agile: 
    - bimU.io Agile Overview: agile/overview.md
    - Get Started with bimU.io Agile: agile/get-started.md
    - Collaborate in a Channel: agile/collaborate-in-a-channel.md
    - Manage Channel Members: agile/manage-channel-members.md
    - Manage and Resolve Issues: agile/manage-and-resolve-issues.md
    - Configure Issue Fields: agile/configure-issue-fields.md
    - Import and Export Issues: agile/import-and-export-issues.md
    - Navigate BIM Models: agile/navigate-bim-models.md
    - Gain Insight from Analytics: agile/gain-insight-from-analytics.md
    - Product Roadmap: agile/product-roadmap.md 
  - Developer Guide: 
    - Getting Started: developer/getting-started.md
    - Project Setup: developer/project-setup.md
    - Initialisation: developer/initialisation.md
    - Authentication: developer/authentication.md
    - Event Handling: developer/event-handling.md
    - Navigation Controls: developer/navigation-controls.md
    - Model Elements: developer/model-elements.md
    - BIM Database: developer/bim-database.md
    - User Interface: developer/user-interface.md
    - Custom Visualisation: developer/custom-visualisation.md
    - Examples: developer/examples.md
    - API Reference: developer/api-reference.md

# Google Analytics
google_analytics:
  - 'UA-143925879-2'
  - auto

extra_css:
  - '//wpcc.io/lib/1.0.2/cookieconsent.min.css'
  - 'css/custom.css'
extra_javascript:
  - '//wpcc.io/lib/1.0.2/cookieconsent.min.js'
  - 'js/initcookieconsent.js'
